package entidades;
// Generated 21 sep. 2022 18:50:42 by Hibernate Tools 4.3.1



/**
 * CausaDevolucion generated by hbm2java
 */
public class CausaDevolucion  implements java.io.Serializable {


     private int id;
     private String nombre;

    public CausaDevolucion() {
    }

    public CausaDevolucion(int id, String nombre) {
       this.id = id;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


