package entidades;
// Generated 21 sep. 2022 18:50:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CondIva generated by hbm2java
 */
public class CondIva  implements java.io.Serializable {


     private Short id;
     private String nombre;
     private Set<Persona> personas = new HashSet<Persona>(0);

    public CondIva() {
    }

	
    public CondIva(String nombre) {
        this.nombre = nombre;
    }
    public CondIva(String nombre, Set<Persona> personas) {
       this.nombre = nombre;
       this.personas = personas;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }




}


