package entidades;
// Generated 21 sep. 2022 18:50:42 by Hibernate Tools 4.3.1



/**
 * LocalRubro generated by hbm2java
 */
public class LocalRubro  implements java.io.Serializable {


     private Integer id;
     private LocalCarniceria localCarniceria;
     private Rubro rubro;

    public LocalRubro() {
    }

    public LocalRubro(LocalCarniceria localCarniceria, Rubro rubro) {
       this.localCarniceria = localCarniceria;
       this.rubro = rubro;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public LocalCarniceria getLocalCarniceria() {
        return this.localCarniceria;
    }
    
    public void setLocalCarniceria(LocalCarniceria localCarniceria) {
        this.localCarniceria = localCarniceria;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }




}


