package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer id;
     private Moneda moneda;
     private String nombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);

    public Pais() {
    }

	
    public Pais(Moneda moneda, String nombre) {
        this.moneda = moneda;
        this.nombre = nombre;
    }
    public Pais(Moneda moneda, String nombre, Set<Empleado> empleados, Set<Empresa> empresas) {
       this.moneda = moneda;
       this.nombre = nombre;
       this.empleados = empleados;
       this.empresas = empresas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }




}


