package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private CondIva condIva;
     private Tipoid tipoid;
     private char tipo;
     private String numIdentificacion;
     private String apellido;
     private String nombre;
     private String nombreFantasia;
     private String razonSocial;
     private String nombreCompleto;
     private String direccion;  
     private Set<PersonaDireccion> personaDireccions = new HashSet<PersonaDireccion>(0);
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Persona() {
    }

	
    public Persona(CondIva condIva, char tipo) {
        this.condIva = condIva;
        this.tipo = tipo;
    }
    public Persona(CondIva condIva, Tipoid tipoid, char tipo, String numIdentificacion, String apellido, String nombre, String nombreFantasia, String razonSocial, Set<PersonaDireccion> personaDireccions, Set<Venta> ventas) {
       this.condIva = condIva;
       this.tipoid = tipoid;
       this.tipo = tipo;
       this.numIdentificacion = numIdentificacion;
       this.apellido = apellido;
       this.nombre = nombre;
       this.nombreFantasia = nombreFantasia;
       this.razonSocial = razonSocial;
       this.personaDireccions = personaDireccions;
       this.ventas = ventas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CondIva getCondIva() {
        return this.condIva;
    }
    
    public void setCondIva(CondIva condIva) {
        this.condIva = condIva;
    }
    public Tipoid getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(Tipoid tipoid) {
        this.tipoid = tipoid;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public String getNumIdentificacion() {
        return this.numIdentificacion;
    }
    
    public void setNumIdentificacion(String numIdentificacion) {
        this.numIdentificacion = numIdentificacion;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreFantasia() {
        return this.nombreFantasia;
    }
    
    public void setNombreFantasia(String nombreFantasia) {
        this.nombreFantasia = nombreFantasia;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Set<PersonaDireccion> getPersonaDireccions() {
        return this.personaDireccions;
    }
    
    public void setPersonaDireccions(Set<PersonaDireccion> personaDireccions) {
        this.personaDireccions = personaDireccions;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

    public String getNombreCompleto(){
        return (tipo == 'P' ? apellido + " " + nombre : nombreFantasia);
    }

    public String getDireccion() {
        if (personaDireccions.size() > 0){
            PersonaDireccion dir=(PersonaDireccion) personaDireccions.iterator().next();
            return dir.getDireccion().concat(" - ").concat(dir.getTelefono()==null ? "" : dir.getTelefono() );
        }
        else
            return null;
    }

    @Override
    public String toString(){
        if (tipo=='P')
            return (apellido== null ? "" : apellido) + " " + (nombre== null ? "" : nombre);            
        else
            return nombreFantasia;            
    }  


}


