package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PorcentajeIva generated by hbm2java
 */
public class PorcentajeIva  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private BigDecimal porcentaje;

    public PorcentajeIva() {
    }

    public PorcentajeIva(String nombre, BigDecimal porcentaje) {
       this.nombre = nombre;
       this.porcentaje = porcentaje;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }




}


