package entidades;
// Generated 21 sep. 2022 18:50:42 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PorcentajeIva generated by hbm2java
 */
public class PorcentajeIva  implements java.io.Serializable {


     private int id;
     private String nombre;
     private BigDecimal porcentaje;

    public PorcentajeIva() {
    }

    public PorcentajeIva(int id, String nombre, BigDecimal porcentaje) {
       this.id = id;
       this.nombre = nombre;
       this.porcentaje = porcentaje;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }




}


