package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Marca marca;
     private Rubro rubro;
     private UnidadMedida unidadMedida;
     private String nombre;
     private String detalle;
     private BigDecimal precioContado;
     private BigDecimal precioLista;
     private Short idIva;
     private char estado;
     private char elaborado;
     private char imprimirComanda;
     private Set<VentaDet> ventaDets = new HashSet<VentaDet>(0);

    public Producto() {
    }

	
    public Producto(Rubro rubro, UnidadMedida unidadMedida, String nombre, BigDecimal precioContado, BigDecimal precioLista, char estado, char elaborado, char imprimirComanda) {
        this.rubro = rubro;
        this.unidadMedida = unidadMedida;
        this.nombre = nombre;
        this.precioContado = precioContado;
        this.precioLista = precioLista;
        this.estado = estado;
        this.elaborado = elaborado;
        this.imprimirComanda = imprimirComanda;
    }
    public Producto(Marca marca, Rubro rubro, UnidadMedida unidadMedida, String nombre, String detalle, BigDecimal precioContado, BigDecimal precioLista, Short idIva, char estado, char elaborado, char imprimirComanda, Set<VentaDet> ventaDets) {
       this.marca = marca;
       this.rubro = rubro;
       this.unidadMedida = unidadMedida;
       this.nombre = nombre;
       this.detalle = detalle;
       this.precioContado = precioContado;
       this.precioLista = precioLista;
       this.idIva = idIva;
       this.estado = estado;
       this.elaborado = elaborado;
       this.imprimirComanda = imprimirComanda;
       this.ventaDets = ventaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    public UnidadMedida getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(UnidadMedida unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public BigDecimal getPrecioContado() {
        return this.precioContado;
    }
    
    public void setPrecioContado(BigDecimal precioContado) {
        this.precioContado = precioContado;
    }
    public BigDecimal getPrecioLista() {
        return this.precioLista;
    }
    
    public void setPrecioLista(BigDecimal precioLista) {
        this.precioLista = precioLista;
    }
    public Short getIdIva() {
        return this.idIva;
    }
    
    public void setIdIva(Short idIva) {
        this.idIva = idIva;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public char getElaborado() {
        return this.elaborado;
    }
    
    public void setElaborado(char elaborado) {
        this.elaborado = elaborado;
    }
    public char getImprimirComanda() {
        return this.imprimirComanda;
    }
    
    public void setImprimirComanda(char imprimirComanda) {
        this.imprimirComanda = imprimirComanda;
    }
    public Set<VentaDet> getVentaDets() {
        return this.ventaDets;
    }
    
    public void setVentaDets(Set<VentaDet> ventaDets) {
        this.ventaDets = ventaDets;
    }

    @Override
    public String toString(){
        return nombre;  
    }  


}


