package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<PersonaDireccion> personaDireccions = new HashSet<PersonaDireccion>(0);
     private Set<LocalCarniceria> localCarnicerias = new HashSet<LocalCarniceria>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Empresa> empresas = new HashSet<Empresa>(0);
     private Set<Localidad> localidads = new HashSet<Localidad>(0);

    public Provincia() {
    }

	
    public Provincia(String nombre) {
        this.nombre = nombre;
    }
    public Provincia(String nombre, Set<PersonaDireccion> personaDireccions, Set<LocalCarniceria> localCarnicerias, Set<Empleado> empleados, Set<Empresa> empresas, Set<Localidad> localidads) {
       this.nombre = nombre;
       this.personaDireccions = personaDireccions;
       this.localCarnicerias = localCarnicerias;
       this.empleados = empleados;
       this.empresas = empresas;
       this.localidads = localidads;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<PersonaDireccion> getPersonaDireccions() {
        return this.personaDireccions;
    }
    
    public void setPersonaDireccions(Set<PersonaDireccion> personaDireccions) {
        this.personaDireccions = personaDireccions;
    }
    public Set<LocalCarniceria> getLocalCarnicerias() {
        return this.localCarnicerias;
    }
    
    public void setLocalCarnicerias(Set<LocalCarniceria> localCarnicerias) {
        this.localCarnicerias = localCarnicerias;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }
    public Set<Empresa> getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set<Empresa> empresas) {
        this.empresas = empresas;
    }
    public Set<Localidad> getLocalidads() {
        return this.localidads;
    }
    
    public void setLocalidads(Set<Localidad> localidads) {
        this.localidads = localidads;
    }




}


