package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rubro generated by hbm2java
 */
public class Rubro  implements java.io.Serializable {


     private Integer id;
     private AreaNegocio areaNegocio;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<SubRubro> subRubros = new HashSet<SubRubro>(0);

    public Rubro() {
    }

	
    public Rubro(AreaNegocio areaNegocio, String nombre) {
        this.areaNegocio = areaNegocio;
        this.nombre = nombre;
    }
    public Rubro(AreaNegocio areaNegocio, String nombre, Set<Producto> productos, Set<SubRubro> subRubros) {
       this.areaNegocio = areaNegocio;
       this.nombre = nombre;
       this.productos = productos;
       this.subRubros = subRubros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AreaNegocio getAreaNegocio() {
        return this.areaNegocio;
    }
    
    public void setAreaNegocio(AreaNegocio areaNegocio) {
        this.areaNegocio = areaNegocio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<SubRubro> getSubRubros() {
        return this.subRubros;
    }
    
    public void setSubRubros(Set<SubRubro> subRubros) {
        this.subRubros = subRubros;
    }

    @Override
    public String toString(){
        return nombre;  
    }  



}


