package entidades;
// Generated 21 sep. 2022 18:50:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<VentaCc> ventaCcs = new HashSet<VentaCc>(0);

    public Tarjeta() {
    }

	
    public Tarjeta(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Tarjeta(int id, String nombre, Set<VentaCc> ventaCcs) {
       this.id = id;
       this.nombre = nombre;
       this.ventaCcs = ventaCcs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<VentaCc> getVentaCcs() {
        return this.ventaCcs;
    }
    
    public void setVentaCcs(Set<VentaCc> ventaCcs) {
        this.ventaCcs = ventaCcs;
    }




}


