package entidades;
// Generated 26 ago. 2022 21:12:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<VentaDet> ventaDets = new HashSet<VentaDet>(0);

    public UnidadMedida() {
    }

	
    public UnidadMedida(String nombre) {
        this.nombre = nombre;
    }
    public UnidadMedida(String nombre, Set<Producto> productos, Set<VentaDet> ventaDets) {
       this.nombre = nombre;
       this.productos = productos;
       this.ventaDets = ventaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<VentaDet> getVentaDets() {
        return this.ventaDets;
    }
    
    public void setVentaDets(Set<VentaDet> ventaDets) {
        this.ventaDets = ventaDets;
    }

    @Override
    public String toString(){
        return nombre;  
    }  



}


